const WA='447449793617';
const modal=document.getElementById('modal'), nav=document.getElementById('navlinks'), hamb=document.getElementById('hamb');
const steps=[...document.querySelectorAll('.step')], progress=document.getElementById('progress'), stepLabel=document.getElementById('stepLabel'), title=document.getElementById('widgetTitle'), sub=document.getElementById('widgetSub'), next=document.getElementById('next'), back=document.getElementById('back'), error=document.getElementById('error'), summary=document.getElementById('summary');
let current=1; const state={services:new Set(),goals:new Set(),budget:''};
function openModal(service=''){modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';current=1;update();if(service){const b=[...document.querySelectorAll('#servicesOptions button')].find(x=>x.dataset.v===service);if(b){b.classList.add('selected');state.services.add(service)}}}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('.open-widget').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.service||'')));
document.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.service)));
document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
hamb.addEventListener('click',()=>{const o=nav.classList.toggle('open');hamb.setAttribute('aria-expanded',o)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
function wireOptions(id,key,multi=true){document.querySelectorAll(`#${id} button`).forEach(b=>b.addEventListener('click',()=>{if(multi){if(state[key].has(b.dataset.v)){state[key].delete(b.dataset.v);b.classList.remove('selected')}else{state[key].add(b.dataset.v);b.classList.add('selected')}}else{document.querySelectorAll(`#${id} button`).forEach(x=>x.classList.remove('selected'));state[key]=b.dataset.v;b.classList.add('selected')}error.textContent='';updateSummary()}))}
wireOptions('servicesOptions','services',true);wireOptions('goalOptions','goals',true);wireOptions('budgetOptions','budget',false);
function update(){steps.forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===current));progress.style.width=`${current*25}%`;stepLabel.textContent=`STEP ${current} OF 4`;const meta=[['What can we help you with?','Select one or more services.'],['What are you looking to achieve?','Choose the outcome that matters most.'],['Tell us about your business','A few details help us make the conversation useful.'],['What level of investment are you considering?','Choose the closest monthly marketing budget.']][current-1];title.textContent=meta[0];sub.textContent=meta[1];back.style.visibility=current===1?'hidden':'visible';next.textContent=current===4?'Continue to WhatsApp →':'Continue →';error.textContent='';updateSummary()}
function updateSummary(){if(current!==4)return;summary.innerHTML=`<b>Your enquiry</b><br>Services: ${[...state.services].join(', ')||'Not selected'}<br>Goals: ${[...state.goals].join(', ')||'Not selected'}<br>Budget: ${state.budget||'Not selected'}`}
function validStep(){if(current===1&&!state.services.size){error.textContent='Please select at least one service.';return false}if(current===2&&!state.goals.size){error.textContent='Please select at least one goal.';return false}if(current===3){const fields=['fName','fBusiness','fEmail','fPhone'];for(const id of fields){if(!document.getElementById(id).value.trim()){error.textContent='Please complete the required fields.';document.getElementById(id).focus();return false}}if(!document.getElementById('fEmail').checkValidity()){error.textContent='Please enter a valid email address.';return false}}if(current===4&&!state.budget){error.textContent='Please select a budget range.';return false}return true}
next.addEventListener('click',()=>{if(!validStep())return;if(current<4){current++;update()}else{sendWhatsApp()}});back.addEventListener('click',()=>{if(current>1){current--;update()}});
function sendWhatsApp(){const v=id=>document.getElementById(id).value.trim();const text=`Hello NovaSpark Creative Ltd,\n\nI'd like to discuss a digital marketing project.\n\nName: ${v('fName')}\nBusiness: ${v('fBusiness')}\nEmail: ${v('fEmail')}\nPhone / WhatsApp: ${v('fPhone')}\nWebsite: ${v('fWebsite')||'Not provided'}\n\nServices:\n${[...state.services].map(x=>'• '+x).join('\n')}\n\nGoals:\n${[...state.goals].map(x=>'• '+x).join('\n')}\n\nMonthly budget: ${state.budget}\n\nProject details:\n${v('fMessage')||'Not provided'}\n\nThank you.`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(text)}`,'_blank','noopener');}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.service,.work-card,.process-grid article,.contact-card').forEach(x=>io.observe(x));
